import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import BottomBar from "@/components/BottomBar";
import MobileNavbar from "@/components/MobileNavbar";
import NoteForm from "@/components/NoteForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="hidden md:block md:w-[200px] lg:w-[250px] ">
          <Sidebar />
        </div>

        <MobileNavbar />
        <main className="container max-w-[360px] mx-auto md:max-w-[500px]">
          <NoteForm />
          {children}
        </main>
        <BottomBar />
      </body>
    </html>
  );
}
